// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("fsprojectile.netcore")>]
[<assembly: AssemblyProductAttribute("fsprojectile")>]
[<assembly: AssemblyDescriptionAttribute("Inspects .fsproj files for F# compiler options and project configuration metadata")>]
[<assembly: AssemblyVersionAttribute("1.0")>]
[<assembly: AssemblyFileVersionAttribute("1.0")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "fsprojectile.netcore"
    let [<Literal>] AssemblyProduct = "fsprojectile"
    let [<Literal>] AssemblyDescription = "Inspects .fsproj files for F# compiler options and project configuration metadata"
    let [<Literal>] AssemblyVersion = "1.0"
    let [<Literal>] AssemblyFileVersion = "1.0"
